# Generated by Django 4.1.3 on 2022-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opentime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
