# Generated by Django 4.1.3 on 2022-12-01 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_restaurant_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='recommend',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
