# Generated by Django 4.1.3 on 2022-12-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_restaurant_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
    ]
