# Generated by Django 4.1.3 on 2022-12-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.FloatField(default=2.5),
        ),
    ]
